### 1. Vector $\vec{v}$ has a value of $[1, 2]$ but then a transformation happens. $\hat{i}$ lands at $[2, 0]$ and $\hat{j}$ lands at $[0, 1.5]$. Where does $\vec{v}$ land?

Well, since we have a diagonal matrix transformation, we can observe that the vector $\vec{v}$ will land at $[2, 3]$.

First off all, lets construct the *transformation* and then apply it to the vector $\vec{v}$ to see where dose it land:

In [1]:
import numpy as np

v1 = np.array([1, 2])
ihat1 = np.array([2, 0])
jhat1 = np.array([0, 1.5])
transformation1 = np.array([ihat1, jhat1]).T
transformation1

array([[2. , 0. ],
       [0. , 1.5]])

In [2]:
transformation1.dot(v1)

array([2., 3.])

### 2. Vector $\vec{v}$ has a value of $[1, 2]$ but then a transformation happens. $\hat{i}$ lands at $[-2, 1]$ and $\hat{j}$ lands at $[1, -2]$. Where does $\vec{v}$ land?

Let's apply the transformation to vector $\vec{v}$ directly:

In [3]:
v1 = np.array([1, 2])
ihat2 = np.array([-2, 1])
jhat2 = np.array([1, -2])
transformation2 = np.array([ihat2, jhat2]).T
transformation2

array([[-2,  1],
       [ 1, -2]])

In [4]:
transformation2.dot(v1)

array([ 0, -3])

### 3. A transformation $\hat{i}$ lands at $[1, 0]$ and $\hat{j}$ lands at $[2, 2]$. What is the determinant of this transformation?

By using `det` numpy linalg function, we can easily calculate the  determinant of this transformation:

In [5]:
ihat3 = np.array([1, 0])
jhat3 = np.array([2, 2])
transformation3 = np.array([ihat3, jhat3]).T
transformation3

array([[1, 2],
       [0, 2]])

In [6]:
np.linalg.det(transformation3)

2.0

### 4. Can two or more linear transformations be done in single linear transformation? Why or why not?

Off course yes! by using matrix multiplication.

### 5. Solve the system of equations for $x$, $y$, and $z$:
$3x + 1y + 0z = 54$<br>
$2x + 4y + 1z = 12$<br>
$3x + 1y + 8z = 6$<br>

to solve the system of equations for $x$, $y$, and $z$, lets extract the
coefficients into matrix $A$, the results of each equation into matrix $B$, and variables into matrix $X$:

$A = \begin{pmatrix} 3 & 1 & 0 \\ 2 & 4 & 1 \\ 3 & 1 & 8 \end{pmatrix}$

$B = \begin{pmatrix} 54 \\ 12 \\ 6 \end{pmatrix}$

$X = \begin{pmatrix} x \\ y \\ z \end{pmatrix}$

And then solving the following equation for $X$:<br>
$AX = B$<br>
$X = BA^{-1}$

In [7]:
A = np.array([[3, 1, 0], [2, 4, 1], [3, 1, 8]])
A

array([[3, 1, 0],
       [2, 4, 1],
       [3, 1, 8]])

In [8]:
B = np.array([54, 12, 6])
B

array([54, 12,  6])

In [9]:
X = np.linalg.inv(A) @ B
X

array([19.8, -5.4, -6. ])

### 6. Is the following matrix linearly dependent? Why or why not?
$\begin{pmatrix}2 & 1 \\ 6 & 3 \end{pmatrix}$

let's check out it's determinant, if it is 0, then it is linearly dependent, other wise it not:

In [10]:
ihat6 = np.array([2, 6])
jhat6 = np.array([1, 3])
M = np.array([ihat6, jhat6]).T
M

array([[2, 1],
       [6, 3]])

In [11]:
np.linalg.det(M)

-3.330669073875464e-16

so, it is  linearly independent.